name: Run Unit Tests

on:
  push:
    branches: [master, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up NASM
      uses: ilammy/setup-nasm@v1

    - name: Compile library
      run: make

    - name: Run unit tests
      working-directory: tests
      run: bash tester.sh

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: tests/results.txt
